### ISSUE TITLE
FR: Move existing date to front of filename

### ISSUE THREAD

**Issue by metbril** [novoid/date2name#28]
Perhaps I've not properly read and tested the code, but if I'm correct, the tool will only preserve (and/or reformat) the date stamp if it is already found at the beginning of the basename.

If so, would it be an option to also detect dates in other places in the base name? So, a file with then name `Invoice Foo Bar 2024-06-20.pdf` would become `2024-06-20 Invoice Foo Bar.pdf` instead? Including the different supported formats (like `--short`).

There are times where I download and save a file days or even longer after I receive it. I some cases, the date is already in the filename.

(Even more advanced would be to intelligently find differently formatted dates like `24-06-2024`, but that is definitely outside the scope of the tool and perhaps more suited for `guess-filename.py`.)

**Comment by novoid** [comment]
Hi,

Sorry, I won't implement that feature wish because this would add complexity which can't be understood any more. For example, how should the tool handle multiple datestamps or datestamp-durations such as `foo bar 2024-06-24--2024-06-29.txt` and similar.

If you do have a datestamp in your filename and you would like to re-format, please do so with tools like `mmv`, `vidir` or similar. Those tools are made for this task.
