### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jagrg** [novoid/date2name#3]
Could you provide instructions on the installation process?

**Comment by novoid** [comment]
There is no special installation process which differs from any other python-script you are installing.

In general, you have to make sure that `date2name` is within the PATH environment either by copying or linking it to, e.g., `/usr/local/bin/`. You might want to add the directory of `date2name` to your PATH environment.

Alternatively, you have to use the absolute path to the date2name-script like,e.g., `/home/jagrg/src/date2name/date2name.py`.

**Comment by jagrg** [comment]
I don't see a .py file. Could you be more explicit. This is what I've done so far.

`$ git clone https://github.com/novoid/date2name.git`

Then I copied the date2name directory to `/usr/local/bin/`

What do I do from there?

If I run `python date2name` I get an error

`date2name: error: invalid usage`

Thanks for your patience

**Comment by novoid** [comment]
Oh, I understand.

`date2name` is a Python script whose file extensions I removed. It is still associated to Python on UNIX-like environments because of a working shebang: http://en.wikipedia.org/wiki/Shebang_%28Unix%29

You almost were successful :-)

Instead of copying the directory of date2name, you should copy the file date2name to `/usr/local/bin/`.

This way, your PATH environment does not get introduces to (only) the directory name but it gets introduced to the `date2name` executable. And of course, the executable flag should be set on `date2name` file if it is not the case yet.

After that, you can start `date2name` even without `python` infront.

**Comment by jagrg** [comment]
Thanks for the explanation. It's working now.
