### ISSUE TITLE
underscore after date sometimes appears and others not

### ISSUE THREAD

**Issue by dimitrisA** [novoid/date2name#4]
file.txt  becomes 2018-11-3_file.txt

whereas

file1518722398544 - Copy somename.jpeg ---> 2018-03-11 file1518722398544 - Copy somename.jpeg

with no underscore.

So, I was wondering, is this a feature? At what times should we expect the _ (underscore) to appear after the file name. Thanks.

**Comment by novoid** [comment]
I totally understand your irritation and I do have to apologize for that.

My personal preference is implemented in the code: if there is a space in the file name already, use a space as a separator character. If not, use an underscore character as a separator.

I was hoping that this is somehow a good idea for the general case. Do you think I should remove this "semi-intelligent" guess and add an additional command line option to choose the separator character?

**Comment by dimitrisA** [comment]
No frustration :) I think it's a useful little software. Currently, I tend to end up with mixed underscores and white space after the date. Sometimes I use append file name or tags first, so I end up with no underscore.

I don't consider it a big deal, though. I also haven't decided if I like underscores or space better. But if it's no trouble, sure, add an option.

**Comment by novoid** [comment]
I added the CLI parameter `--delimiter` where you can define any arbitrary string as delimiter.

Please notice that date2name might not be able to recognize this as a delimiter character if it does not start with space, minus or underscore.

In a shell, you can define something like `alias date2name="date2name --delimiter=\"_\""` in order to get your underscore as the default delimiter.

HTH
